---
title: "AnVIL_Vignette"
format: html
editor: source
---

## `litllm` AnVIL Vignette

```{r}
author_df <- ll_extract_authors("pdf/")

# Check for dupes, and perhaps delete any copies from the pdf directory
check_this_authors <- author_df %>% count(paper_id, title)

# Get institutions only from each author blurb & store it
author_df$inst <- ll_pull_institutions(author_df$auth)
readr::write_rds(author_df, "author_df_insts.rds")

# Get distinct institutions
distinct_insts <- unique(author_df$inst)
```

```{r}
# Get info -- what kind of institution?
in_US <- ll_check_institution_type(distinct_insts, logical_check = "in the United States")
is_R1 <- ll_check_institution_type(distinct_insts, logical_check = "a Carnegie Classification R1: Doctoral Universities – Very high research activity institution")
is_R2 <- ll_check_institution_type(distinct_insts, logical_check = "a Carnegie Classification R2: Doctoral Universities – High research activity institution")
is_dpu <- ll_check_institution_type(distinct_insts, logical_check = "a Carnegie Classification D/PU: Doctoral/Professional Universities institution")
is_m <- ll_check_institution_type(distinct_insts, logical_check = "a Carnegie Classification M: Master’s Colleges and Universities institution")
is_pui <- ll_check_institution_type(distinct_insts, logical_check = "a Primarily Undergraduate Institution")
is_msi <- ll_check_institution_type(distinct_insts, logical_check = "a Minority Serving Institution")
is_gov <- ll_check_institution_type(distinct_insts, logical_check = "a federal or state government entity")
is_co <- ll_check_institution_type(distinct_insts, logical_check = "a company in private sector")
is_np <- ll_check_institution_type(distinct_insts, logical_check = "a nonprofit institution without a university")

about_insts <-
  left_join(in_US, is_R1) %>% 
  left_join(is_R2) %>% 
  left_join(is_dpu) %>% 
  left_join(is_m) %>% 
  left_join(is_pui) %>% 
  left_join(is_msi) %>% 
  left_join(is_gov) %>% 
  left_join(is_co) %>% 
  left_join(is_np)

# Some decision logic based on T/F responses
about_insts <-
  about_insts %>%
  mutate(type = "TEMP") %>%
  mutate(
    type = case_when(
      in_the_united_states == FALSE ~ "International Institution",
      a_minority_serving_institution == TRUE ~ "MSI",
      type == "TEMP" & a_carnegie_classification_r1_doctoral_universities_very_high_research_activity_institution == TRUE ~ "R1 Institution / Doctoral/Professional",
      type == "TEMP" & a_carnegie_classification_d_pu_doctoral_professional_universities_institution == TRUE ~ "R1 Institution / Doctoral/Professional",
      type == "TEMP" & a_carnegie_classification_r2_doctoral_universities_high_research_activity_institution == TRUE ~ "R2",
      type == "TEMP" & a_carnegie_classification_m_master_s_colleges_and_universities_institution == TRUE ~ "Master's",
      type == "TEMP" & a_primarily_undergraduate_institution == TRUE ~ "PUI",
      type == "TEMP" & a_federal_or_state_government_entity == TRUE ~ "Government",
      type == "TEMP" & a_company_in_private_sector == TRUE ~ "Private Company",
      type == "TEMP" & a_nonprofit_institution_without_a_university == TRUE ~ "Nonprofit Institution",
      TRUE ~ "Other"
    )
  )

# Save for later
readr::write_csv(about_insts, "insts_key.csv")
```

```{r}
# Do some manual editing
about_insts <- read_csv("insts_key.csv")

corrected_R1s <-
  c(
    "Broad Institute",
    "Undiagnosed Diseases Network",
    "University of Maine",
    "University of California Los Angeles",
    "Johns Hopkins",
    "Harvard",
    "UC Santa Cruz Genomics Institute",
    "Colorado School of Public Health",
    "Duke-Margolis Center for Health Policy",
    "Albert Einstein College of Medicine",
    "University of South Carolina",
    "University of California San Francisco",
    "Brown University",
    "University of Maryland Institute for Genome Sciences",
    "University of Southern California",
    "Icahn School of Medicine at Mount Sinai",
    "University of North Carolina at Chapel Hill",
    "Yale University",
    "University of Cincinnati"
  )

corrected_MSIs <-
  c(
    "University of Washington",
    "City University of New York",
    "Rutgers-Robert Wood Johnson Medical School",
    "Loma Linda University School of Medicine",
    "University of Arizona",
    "University of California, Santa Cruz",
    "University of California Santa Cruz",
    "UC Santa Cruz Genomics Institute",
    "UC Davis",
    "University of California, Davis",
    "University of California, Berkeley",
    "University of California Berkeley",
    "University of California, San Diego",
    "University of California Santa Barbara",
    "University of California, Irvine",
    "UC Irvine",
    "University of Texas at Austin",
    "University of Colorado Anschutz Medical Campus",
    "University of Colorado Anschutz School of Medicine"
  )

corrected_R2 <-
  c("IIT")

corrected_np <-
  c(
    "UAB Medicine Enterprise",
    "Geisinger",
    "Kaiser Permanente",
    "Jackson Lab",
    "MDI Biological Laboratory"
  )

corrected_i <-
  c("Princess Margaret Cancer Centre")

about_insts_clean <-
  about_insts %>%
  mutate(
    type_clean =
      case_when(
        type != "International Institution" &
          str_detect(name, paste(corrected_R1s, collapse = "|")) ~ "R1 Institution / Doctoral/Professional",
        TRUE ~ type
      )
  ) %>%
  mutate(type_clean =
           case_when(str_detect(
             name, paste(corrected_MSIs, collapse = "|")
           ) ~ "MSI", TRUE ~ type_clean)) %>%
  mutate(type_clean =
           case_when(
             str_detect(name, paste(corrected_np, collapse = "|")) ~ "Nonprofit Institution",
             TRUE ~ type_clean
           )) %>%
  mutate(type_clean =
           case_when(str_detect(name, paste(
             corrected_R2, collapse = "|"
           )) ~ "R2", TRUE ~ type_clean)) %>%
  mutate(type_clean =
           case_when(
             str_detect(name, paste(corrected_i, collapse = "|")) ~ "International Institution",
             TRUE ~ type_clean
           )) %>%
  tidyr::drop_na(name)

readr::write_csv(about_insts_clean, "insts_key_clean.csv")

author_df_type <-
  author_df %>%
  left_join(about_insts_clean,
            by = c("inst" = "name"),
            relationship = "many-to-many")
auth_clean <-
  str_match(author_df_type$auth, "^(.+?),")[, 2]
author_df_type <- cbind(author_df_type, auth_clean)

unique_auth_inst <- author_df_type %>% count(auth_clean, type_clean) %>% arrange(desc(n))

auth_plot <- author_df_type %>% distinct(type_clean, auth_clean) %>% tidyr::drop_na(type_clean)
auth_plot$type_clean <- factor(
  auth_plot$type_clean,
  levels = c(
    "R1 Institution / Doctoral/Professional",
    "International Institution",
    "Nonprofit Institution",
    "MSI",
    "Government",
    "Private Company",
    "PUI",
    "R2"
  )
)

ggplot(auth_plot, aes(type_clean, fill = type_clean)) +
  geom_bar() +
  geom_text(stat = "count", aes(label = after_stat(count)), nudge_y = 17) +
  theme_minimal() +
  theme(
    axis.title = element_blank(),
    axis.text.x = element_blank(),
    legend.title = element_blank()
  ) +
  labs(title = "AnVIL First 100 Citations - Who is citing AnVIL?", subtitle = "Unique author and institution combinations")

write_csv(about_insts, "inst_key_2.csv")
```

